### ISSUE TITLE
Missing 'BoxBounds' Class

### ISSUE THREAD

**Issue by ReubenDo** [LIVIAETS/boxes_tightness_prior#1]
Dear Hoel,

Thank you for sharing your code. I have the following error when running your code:
`AttributeError: module 'bounds' has no attribute 'BoxBounds'`

Could you add the BoxBounds class in bounds, please?

Thanks!
Cheers

**Comment by HKervadec** [comment]
Ah yes seems I trimmed too harshly (I had some plagiarism issue in the past, now I have to remove any code from unpublished papers). Thanks for pointing that out!

```python
class BoxBounds():
    def __init__(self, **kwargs):
        self.margins: Tensor = torch.Tensor(kwargs['margins'])
        assert len(self.margins) == 2
        assert self.margins[0] <= self.margins[1]

    def __call__(self, image: Tensor, target: Tensor, weak_target: Tensor, filename: str) -> Tensor:
        c = len(weak_target)
        box_sizes: Tensor = torch.einsum("cwh->c", weak_target)[..., None].type(torch.float32)

        bounds: Tensor = box_sizes * self.margins

        res = bounds[:, None, :]
        assert res.shape == (c, 1, 2)
        assert (res[..., 0] <= res[..., 1]).all()

        return res
```
That should do it, I'll add it in the repository on Monday (which is due, anyway, for some update/clean-up)

**Comment by ReubenDo** [comment]
Great, thanks!
FYI I sent you an email with questions regarding the paper at hoel at kervadec.science few days ago in case you haven’t seen it.
Cheers,
Reuben

**Comment by HKervadec** [comment]
>  FYI I sent you an email with questions regarding the paper at hoel at kervadec.science few days ago in case you haven’t seen it.

yeah I saw it, I'm resting after the MIDL deadline but I'll reply on Monday

**Comment by HKervadec** [comment]
Added in bae20f634436d5710d5c30016984b750a57b9845
