### ISSUE TITLE
Upgrade to latest python/pytorch version

### ISSUE THREAD

**Issue by HKervadec** [LIVIAETS/boxes_tightness_prior#3]
Also include latest makefile tricks for readability

**Comment by jingyuerY** [comment]
python3.8 conflict with “pydensecrf”
when I install package “pydensecrf”，a mistake will happen
![1](https://user-images.githubusercontent.com/43965944/113401037-5945dd00-93d5-11eb-9ef3-820db12b71c2.png)

**Comment by HKervadec** [comment]
I do not use pip, and I need to upgrade that repo (I've myself moved to python 3.9 in the meantime).  

What command did you use to install? Did you try to compile from sources (with pip) rather than installing a pre-built binary? i.e.:
```sh
pip install git+https://github.com/lucasb-eyer/pydensecrf.git
```


BTW: pydenseCRF is used only for deepcut (not my method, as I wanted to keep it simple for comparison).

**Comment by jingyuerY** [comment]
I used "pip install pydensecrf"\"conda install pydensecrf"\"conda install -c conda-forge pydensecrf", and all of them have the above problems, but when I change pathon to 3.6, it will be ok. (what's the impact of not using the latest python version?
Also, when I run "make -f prostate.make <really> NET=Dimwit EPC=5 DEBUG=--debug", there will be this error:
![2](https://user-images.githubusercontent.com/43965944/113800861-48f18180-978a-11eb-8b44-621c633a963f.png)
